create table
  public.chat (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    room_id bigint null,
    constraint chat_pkey primary key (id),
    constraint chat_room_id_fkey foreign key (room_id) references rooms (id) on update cascade on delete cascade
  ) tablespace pg_default;