create table
  public.room_events (
    id bigint generated by default as identity,
    timestamp timestamp with time zone not null default now(),
    use_id uuid null,
    type text null,
    payload json null,
    constraint room_events_pkey primary key (id),
    constraint room_events_use_id_fkey foreign key (use_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;