create table
  public.rooms (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    created_by uuid null default auth.uid (),
    name text null,
    capsule_id uuid null,
    params json null,
    constraint rooms_pkey primary key (id),
    constraint rooms_created_by_fkey foreign key (created_by) references auth.users (id) on update cascade on delete cascade,
    constraint rooms_capsule_id_fkey foreign key (capsule_id) references capsules (id) on update cascade on delete set null
  ) tablespace pg_default;